version: '3.8'

services:
  ravendb:
    image: ravendb/ravendb
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
    volumes:
      - ravendb-data:/opt/RavenDB/Server/RavenData
    ports:
      - "8080:8080"

volumes:
  ravendb-data:
